# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
name: Run Test CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: 'Install Yarn'
        uses: actions/checkout@v2

      - name: 'Install Dependencies'
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: 'Run Tests'
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test-all
